const data = {
  products: [
    {
      name: "Ring 1",
      slug: "ring1",
      category: "rings",
      image: "/images/ring1.jpg",
      price: 2500,
      brand: "Tiffany & Co.",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Ring",
    },
    {
      name: "Ring 2",
      slug: "ring2",
      category: "rings",
      image: "/images/ring2.jpg",
      price: 2500,
      brand: "Tiffany & Co.",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Ring",
    },
    {
      name: "Ring 3",
      slug: "ring3",
      category: "rings",
      image: "/images/ring3.jpg",
      price: 2500,
      brand: "Tiffany & Co.",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Ring",
    },
    {
      name: "Ring 4",
      slug: "ring4",
      category: "rings",
      image: "/images/ring4.jpg",
      price: 2500,
      brand: "Tiffany & Co.",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Ring",
    },
    {
      name: "Ring 5",
      slug: "ring5",
      category: "rings",
      image: "/images/ring5.jpg",
      price: 2500,
      brand: "Tiffany & Co.",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Ring",
    },
    {
      name: "Ring 6",
      slug: "ring6",
      category: "rings",
      image: "/images/ring6.jpg",
      price: 2500,
      brand: "Tiffany & Co.",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Ring",
    },
    {
      name: "Ring 7",
      slug: "ring7",
      category: "rings",
      image: "/images/ring7.jpg",
      price: 2500,
      brand: "Tiffany & Co.",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Ring",
    },
    {
      name: "Necklace 1",
      slug: "necklace1",
      category: "necklaces",
      image: "/images/necklace1.jpg",
      price: 3700,
      brand: "Tiffany & Co.",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Necklace",
    },
    {
      name: "Necklace 2",
      slug: "necklace2",
      category: "necklaces",
      image: "/images/necklace2.jpg",
      price: 3700,
      brand: "Tiffany & Co.",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Necklace",
    },
    {
      name: "Necklace 3",
      slug: "necklace3",
      category: "necklaces",
      image: "/images/necklace3.jpg",
      price: 3700,
      brand: "Tiffany & Co.",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Necklace",
    },
    {
      name: "Necklace 4",
      slug: "necklace4",
      category: "necklaces",
      image: "/images/necklace4.jpg",
      price: 3700,
      brand: "Tiffany & Co.",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Necklace",
    },
    {
      name: "Necklace 5",
      slug: "necklace5",
      category: "necklaces",
      image: "/images/necklace5.jpg",
      price: 3700,
      brand: "Tiffany & Co.",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Necklace",
    },
    {
      name: "Earrings 1",
      slug: "earrings1",
      category: "earrings",
      image: "/images/earrings1.jpg",
      price: 700,
      brand: "Blue Diamond",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Pair of Earrings",
    },
    {
      name: "Earrings 2",
      slug: "earrings2",
      category: "earrings",
      image: "/images/earrings2.jpg",
      price: 700,
      brand: "Blue Diamond",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Pair of Earrings",
    },
    {
      name: "Earrings 3",
      slug: "earrings3",
      category: "earrings",
      image: "/images/earrings3.jpg",
      price: 700,
      brand: "Blue Diamond",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Pair of Earrings",
    },
    {
      name: "Earrings 4",
      slug: "earrings4",
      category: "earrings",
      image: "/images/earrings4.jpg",
      price: 700,
      brand: "Blue Diamond",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Pair of Earrings",
    },
    {
      name: "Earrings 5",
      slug: "earrings5",
      category: "earrings",
      image: "/images/earrings5.jpg",
      price: 700,
      brand: "Blue Diamond",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Pair of Earrings",
    },
    {
      name: "Earrings 6",
      slug: "earrings6",
      category: "earrings",
      image: "/images/earrings6.jpg",
      price: 700,
      brand: "Blue Diamond",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Pair of Earrings",
    },
    {
      name: "Earrings 7",
      slug: "earrings7",
      category: "earrings",
      image: "/images/earrings7.jpg",
      price: 700,
      brand: "Blue Diamond",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Pair of Earrings",
    },
    {
      name: "Bracelet 1",
      slug: "bracelet1",
      category: "bracelets",
      image: "/images/bracelet1.jpg",
      price: 500,
      brand: "Pandora",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Bracelet",
    },
    {
      name: "Bracelet 2",
      slug: "bracelet2",
      category: "bracelets",
      image: "/images/bracelet2.jpg",
      price: 500,
      brand: "Pandora",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Bracelet",
    },
    {
      name: "Bracelet 3",
      slug: "bracelet3",
      category: "bracelets",
      image: "/images/bracelet3.jpg",
      price: 500,
      brand: "Pandora",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Bracelet",
    },
    {
      name: "Bracelet 4",
      slug: "bracelet4",
      category: "bracelets",
      image: "/images/bracelet4.jpg",
      price: 500,
      brand: "Pandora",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Bracelet",
    },
    {
      name: "Bracelet 5",
      slug: "bracelet5",
      category: "bracelets",
      image: "/images/bracelet5.jpg",
      price: 500,
      brand: "Pandora",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Bracelet",
    },
    {
      name: "Bracelet 6",
      slug: "bracelet6",
      category: "bracelets",
      image: "/images/bracelet6.jpg",
      price: 500,
      brand: "Pandora",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Bracelet",
    },
    {
      name: "Bracelet 7",
      slug: "bracelet7",
      category: "bracelets",
      image: "/images/bracelet7.jpg",
      price: 500,
      brand: "Pandora",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Bracelet",
    },
    {
      name: "Bracelet 8",
      slug: "bracelet8",
      category: "bracelets",
      image: "/images/bracelet8.jpg",
      price: 500,
      brand: "Pandora",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Bracelet",
    },
    {
      name: "Bracelet 9",
      slug: "bracelet9",
      category: "bracelets",
      image: "/images/bracelet9.jpg",
      price: 500,
      brand: "Pandora",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Bracelet",
    },
    {
      name: "Bracelet 10",
      slug: "bracelet10",
      category: "bracelets",
      image: "/images/bracelet10.jpg",
      price: 500,
      brand: "Pandora",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Bracelet",
    },
    {
      name: "Watch 1",
      slug: "watch1",
      category: "watches",
      image: "/images/watch1.jpg",
      price: 1000,
      brand: "Panerai",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Watch",
    },
    {
      name: "Watch 2",
      slug: "watch2",
      category: "watches",
      image: "/images/watch2.jpg",
      price: 1000,
      brand: "Zenith",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Watch",
    },
    {
      name: "Watch 3",
      slug: "watch3",
      category: "watches",
      image: "/images/watch3.jpg",
      price: 1000,
      brand: "Ulysse Nardin",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Watch",
    },
    {
      name: "Watch 4",
      slug: "watch4",
      category: "watches",
      image: "/images/watch4.jpg",
      price: 1000,
      brand: "Ulysse Nardin",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Watch",
    },
    {
      name: "Watch 5",
      slug: "watch5",
      category: "watches",
      image: "/images/watch5.jpg",
      price: 1000,
      brand: "Patek Philippe",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Watch",
    },
    {
      name: "Watch 6",
      slug: "watch6",
      category: "watches",
      image: "/images/watch6.jpg",
      price: 1000,
      brand: "Cartier",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Watch",
    },
    {
      name: "Watch 7",
      slug: "watch7",
      category: "watches",
      image: "/images/watch7.jpg",
      price: 1000,
      brand: "Cartier",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Watch",
    },
    {
      name: "Cuffling 1",
      slug: "cuffling1",
      category: "cufflings",
      image: "/images/cufflings1.jpg",
      price: 200,
      brand: "Cartier",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Cufflings",
    },
    {
      name: "Cuffling 2",
      slug: "cuffling2",
      category: "cufflings",
      image: "/images/cufflings2.jpg",
      price: 200,
      brand: "Cartier",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Cufflings",
    },
    {
      name: "Cuffling 3",
      slug: "cuffling3",
      category: "cufflings",
      image: "/images/cufflings3.jpg",
      price: 200,
      brand: "Cartier",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Cufflings",
    },
    {
      name: "Cuffling 4",
      slug: "cuffling4",
      category: "cufflings",
      image: "/images/cufflings4.jpg",
      price: 200,
      brand: "Cartier",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Cufflings",
    },
    {
      name: "Cuffling 5",
      slug: "cuffling5",
      category: "cufflings",
      image: "/images/cufflings5.jpg",
      price: 200,
      brand: "Cartier",
      rating: 4.5,
      countInStock: 1,
      description: "Beautiful Cufflings",
    },
  ],
};

export default data;
